build_from:
  amd64: node:24-alpine
  aarch64: node:24-alpine
labels:
  org.opencontainers.image.title: Podwaffle
  org.opencontainers.image.description: Self-hosted podcast server and web client
  org.opencontainers.image.source: https://github.com/podwaffle/podwaffle
args:
  TEMPIO_VERSION: "2024.11.2"
  PODWAFFLE_REF: "716df5271398bc30c6bcf7d8cccd6e1ab329354b"
